version: '3'

services:
  jekyll:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec jekyll serve --host 0.0.0.0
    volumes:
      - .:/reputationvip.github.io
    ports:
      - 80:4000
